"use strict";

export const ACT_DELETE_ARTICLE = "DELETE_ARTICLE";

export const ACT_LOAD_ALL_ARTICLES_OK   = "ACT_LOAD_ALL_ARTICLES_OK";
export const ACT_LOAD_ALL_ARTICLES_FAIL = "ACT_LOAD_ALL_ARTICLES_FAIL";
export const ACT_LOAD_ARTICLE_OK        = "ACT_LOAD_ARTICLE_OK";
export const ACT_LOAD_ARTICLE_FAIL      = "ACT_LOAD_ARTICLE_FAIL";

export const ACT_ADD_COMMENT = "ACT_ADD_COMMENT";

export const ACT_LOAD_COMMENTS_OK   = "ACT_LOAD_COMMENTS_OK";
export const ACT_LOAD_COMMENTS_FAIL = "ACT_LOAD_COMMENTS_FAIL";
